version: "3.9"
services:
  message-api:
    image: mvon38/xyz:latest
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "5000:80"
  unit-tests:
    build:
      context: .
      dockerfile: docker/unit-tests.Dockerfile
  karate:
    network_mode: host
    build:
      context: ./karate
      dockerfile: ./Dockerfile
