steps:
  - label: ":docker: Build and Push Image"
    plugins:
      - docker-compose#v4.12.0:
          build: message-api
          image-repository: index.docker.io/mvon38/xyz
  - label: ":dotnet: Run Unit Tests"
    plugins:
      - docker-compose#v4.12.0:
          run: unit-tests
  - label: ":eks: :k8s: Deploy to Kubernetes"
    commands:
      - cd tanka
      - tk apply --auto-approve always environments/default
      - buildkite-agent meta-data set "xyz_api_url" "$(kubectl get svc xyz)"
  - label: ":karate: Run Karate Api Tests"
    plugins:
      - docker-compose#v4.12.0:
          run: karate
          propagate-environment: true
          mount-buildkite-agent: true
          command: [ "--env=buildkite", "./message.feature" ]

