steps:
  - label: ":docker: Build and Push Image"
    plugins:
      - docker-compose#v4.12.0:
          build: message-api
          image-repository: index.docker.io/mvon38/xyz
  - label: ":dotnet: Run Unit Tests"
    plugins:
      - docker-compose#v4.12.0:
          run: unit-tests
  - label: ":eks: :k8s: Deploy to Kubernetes"
    commands:
      - cd tanka
      - tk apply --auto-approve always --ext-str tag=$$BUILDKITE_PIPELINE_NAME-message-api-build-$$BUILDKITE_BUILD_NUMBER environments/default
      - sleep 5
      - buildkite-agent meta-data set "xyz_api_url" "$(kubectl get svc xyz -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
  - label: ":karate: Run Karate Api Tests"
    plugins:
      - docker-compose#v4.12.0:
          run: karate
          propagate-environment: true
          mount-buildkite-agent: true

